# Generated by Django 5.1.4 on 2024-12-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysishistory_usernotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('signal', 'Sinal de Trading'), ('alert', 'Alerta de Preço'), ('risk', 'Aviso de Risco')], max_length=10)),
                ('trading_type', models.CharField(choices=[('futures', 'Futures'), ('day', 'Day Trading'), ('swing', 'Swing'), ('position', 'Position')], max_length=10)),
                ('signal_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda'), ('neutral', 'Neutro')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('importance', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analysis_tr_user_id_2513ab_idx'), models.Index(fields=['notification_type', 'trading_type'], name='analysis_tr_notific_642b55_idx')],
            },
        ),
    ]
